# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 870a946615cabda4e958b48482f35b7556514ac39675b9114e2f2ff249f324739ecaf9ac4d6da34bd822547b804b92cc1f9849d8da11df4644111cac6c98795c

test:
  secret_key_base: 8a37245df4dcf9f557c839a47339f3247d337e8c0e46d02c7ef5a84f6bb65786e1bcc064504b1783262c0c2ed149c5908aaeba4cb63ee468c267a91dd21dc4c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 983h0fui2ehfuhxisjniyrgvcoqeb4ynr7344rncu3hnreuiwngs3y48oybhdsfhbvruh2h73rniu24fho4fruy4rflu4rvr4ohcrnuoeuhdicqhqeui2827384fybufewhbr78fdusdv6fydsyhveh4u3